### ISSUE TITLE
5分の休憩中に次の曲が探せるようにしてほしいです。

### ISSUE THREAD

**Issue by AkoNakayama** [pandeiro245/245cloud#169]
5分休憩中に曲が探せるととてもよいリズムでやれるので、おねがいします！

**Comment by pandeiro245** [comment]
# TODO
* [ ] 一度 `$dom.hide()`したdomを`$dom.show()` する
* [ ] 「この曲で集中」というボタンの文言を「次はこの曲で集中」に変更
* [ ] 上記を押すとURLのhashがそれに変わり、alertか何かで「次は◯◯を再生します」とかする？
