### ISSUE TITLE
toggl連携

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/245cloud#204]
# TODO
- [ ] 本当にAPI token投げるしかないのか、OAuth対応していないのか確認する
- [x] localStorage['toggl_token'] が入っていなければpromptを実行
- [ ] chromeでpromtが出た時に「再度表示しない」にするとapi tokenが不正でもpromptが出ない問題
- [ ] localStorageはセキュリティ的に心配なのでcookieを使うことを検討
- [x] API通信処理のエラー処理
- [x] 24分がはじまる、かつtogglがストップ状態なら直近のタスクでtoggl再開
- [x] 24分が終わったらtogglも止まる
# 参考

https://github.com/toggl/toggl_api_docs

**Comment by KeitaShiya** [comment]
:+1:

**Comment by pandeiro245** [comment]
gem: https://github.com/kanet77/togglv8

**Comment by pandeiro245** [comment]
うーん

https://github.com/kanet77/togglv8/blob/master/togglv8.gemspec#L26

こうなってるのにこうなる

```
➜  245cloud git:(issue-204) ✗ rails c
/Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/togglv8-1.0.4/lib/togglv8.rb:5:in `require': cannot load such file -- awesome_print (LoadError)
        from /Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/togglv8-1.0.4/lib/togglv8.rb:5:in `<top (required)>'
        from /Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `require'
        from /Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `each'
        from /Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `block in require'
        from /Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `each'
        from /Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `require'
        from /Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler.rb:134:in `require'
        from /Users/nishiko/git/245cloud/config/application.rb:7:in `<top (required)>'
        from /Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:141:in `require'
        from /Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
        from /Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:67:in `console'
        from /Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/nishiko/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by pandeiro245** [comment]
コメントアウトしたら動いた

**Comment by pandeiro245** [comment]
@KeitaShiya togglってOAuthログインないのかな？
https://github.com/kanet77/togglv8
ではAPI token投げる感じになってる…

**Comment by KeitaShiya** [comment]
@pandeiro245 https://toggl.com/app/profile からユーザーが自分で取得してくるしかないかんじっぽいですねぇ...
https://github.com/toggl/toggl_api_docs#api-token

**Comment by pandeiro245** [comment]
@KeitaShiya 現状でも
http://245cloud.com/?toggl=1
で動くはず。サーバにapi-token保存したくないから
取り急ぎlocalStorageに保存してもらう感じにしてるけど
何かいい案あれば是非！

**Comment by KeitaShiya** [comment]
すごい！！！ありがとうございます！！
