### ISSUE TITLE
APIを増やす

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/245cloud#252]
# DONE

* [x] `GET /api/workloads/yours`
* [x] `GET /api/workloads/dones`
* [x] `GET /api/workloads/doings`
* [x] `GET /api/workloads/chattings`
* [x] `POST /api/comments`
* [x] `GET /api/comments`
* [x] `POST /api/comments`

# TODO
* [x] `GET /api/users/#{facebook_id}/workloads/musics` 自分が聞いた音楽（たくさん聞いている順）
* [ ] 自分が聞いた音楽（再生順）
* [ ] 特定の期間中の達成数ランキング

**Comment by pandeiro245** [comment]
残りは別issue化
