### ISSUE TITLE
超簡易pivotal trackerみたいなやつを開発合宿中に作りたい

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/245cloud#313]
# TODO
- [ ] 245cloud-appからだとpromptが出ない件
- [x] 実績が見積を超えた場合は残数を引かない
- [ ] 稼働予定ポモ数がモックになっているのをなんとかする？（理想はGoogleカレンダー連携）
- [x] 実績ポモ数がカウントアップしない時がある（される時もある）
- [x] 途中でteam_idが変わったtaskがあるとエラーになる件
# 解決したい課題
- 次にどのタスクで集中すべきかをサジェストして欲しい
# 仕様
- TODOを追加できる（URL、締切時間）
- TODOにかかる見積ポモ数、トップにある草（あれって名前なんだっけ）にその日できる見積ポモ数を登録できる
- トップにある草は翌月まで表示させる（現在は当月まで）
- 上記２つの情報を使って次にやるべきTODOをサジェストしてくれる
- TODO毎にポモれて、ポモったTODOのworkload_countがカウントアップされる
# サジェストロジック
- TODOの期限までにできるポモ数をTODOにかかる見積ポモ数が上回っている場合、そのTODOを無条件に表示（複数ありえる）
- 上記ではない場合、上記のようなやつを重み付けした確率でランダムにサジェスト
# DB設計
- `rails g model Issue user:references key:string estimated:integer worked:integer deadline:datetime`
- `rails g model Daily user:references estimated:integer workload_count`
- `rails g model DailyWorkload daily:references workload:references`
- `rails g model IssueWorkload issue:references workload:references`
# その他思うこと
- boolean型のカラム名を`is_done`とするのは古くて`done`とすべきらしい。理由は`done?`みたいなメソッドを作りたい時に`is_done?`みたいになっちゃうから
# セキュリティ

個人サービスなので機密情報（メアドとか）を一切持たない運用にしている。
なのでTODOにもタイトルや本文は入力できずURLのみにする
# TODO
- [x] `Issue`モデルの追加
- [x] `Issue`の`estimated`から`workload_count`を引いた下図の重み付けだけでサジェストしてみる
- [x] `workload_count`のカウントアップロジックを追加
- [ ] `git grep Util.time`して秒なのかマイクロ秒なのかを確認
- [x] `Issue`の`estimate`と`deadline`の再編集
# 将来機能

trello, GitHub issues, pivotal trackerなどとAPIで連携 
→Issueモデルと同期させる

**Comment by fukajun** [comment]
URLしか入力できなかったとしても、公開不可なURLは入力されたりする気もしますね。

**Comment by fukajun** [comment]
doneというboolean型のカラムを作るのはいいのだけど、よくやるのは `completed_at` などのDate型のカラムを用意してそこに完了日時をいれて 
```
def done?
  !!completed_at
end
```
とする感じですね。

**Comment by pandeiro245** [comment]
@fukajun コメントいま気づいた！！
```
irb(main):065:0> !!Time.now
=> true
```
頭にビックリマーク２つ付けたら真偽値になるんですね！

**Comment by pandeiro245** [comment]
@fukajun 245cloud本体の`Workload`の`is_done`も`completed_at`に変更して本当に`created_at`からだいたい24分後の時間が入ってるか検証できるようにしておいてもいいかもですね！
