### ISSUE TITLE
nginx, unicorn and mysqlが止まっても自動起動

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/245cloud#344]
現在の設定：https://gist.github.com/honjo2/5023446

# TODO
* [ ] nginx自動再起動：`sudo /etc/init.d/nginx start`
* [ ] unicorn自動再起動：`unicorn -c config/unicorn.conf -D`
* [x] mysql自動再起動：`sudo chkconfig mysqld on`
