### ISSUE TITLE
dev.245cloud.comを作ってcloud9で他の人も入れるようにする

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/245cloud#381]
# TODO
* [x] インスタンスコピーする
* [x] Cloud9から繋ぐ
* [x] node入れる：https://qiita.com/oishihiroaki/items/bc663eb1282d87c46e97
* [ ] Cloud9 IDE入れる
* [ ] http://245cloud.com/ で動かす
* [ ] dev.245cloud.com 上にSSL入れる
* [ ] https://245cloud.com/ で動かす
